VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
# CONSOLE_ENABLE = no

RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = aw20216s
VIALRGB_ENABLE = yes

LTO_ENABLE = yes
